const $ = s => document.querySelector(s);
let criteria = [], profiles = [], jockeys = [], currentRaceId = null;
const raceBody = $('#horses');
const fields = ['birthdate','sex','robe','father','mother','trainer','owner','jockey','jockeyAlt','value','lastValue','discipline','speed','endurance','constance','tactic','distancePref','groundPref','potential','deferrage','notes'];

async function api(path, method='GET', data){
  const res = await fetch(path,{method,headers:{'Content-Type':'application/json'},body:data ? JSON.stringify(data) : undefined});
  const json = await res.json(); if(!res.ok) throw new Error(json.error || 'Une erreur est survenue'); return json;
}
function value(id){return $('#'+id).value.trim()}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function profileFieldId(key){return 'profile-'+key.replace(/[A-Z]/g, letter=>'-'+letter.toLowerCase())}
function ageOf(date){if(!date)return ''; const d=new Date(date); if(Number.isNaN(d))return ''; return new Date().getFullYear()-d.getFullYear()-(new Date()<new Date(new Date().getFullYear(),d.getMonth(),d.getDate())?1:0)}
function profileOptions(selected=''){return `<option value="">Saisir pour cette course…</option>${profiles.map(p=>`<option value="${p.id}" ${String(p.id)===String(selected)?'selected':''}>${escapeHtml(p.name)}</option>`).join('')}`}
function escapeHtml(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function scoreInputs(scores={}, kind='race') {return criteria.map(([key,label])=>`<label>${label}<input class="${kind==='race'?'race-score':'profile-score'}" data-key="${key}" type="number" min="0" max="10" step="0.5" value="${scores[key]??''}"></label>`).join('')}
function addHorse(h={}){
  const tr=document.createElement('tr'); tr.dataset.profileId=h.profileId||'';
  tr.innerHTML=`<td><input class="horse-num" type="number" min="1" value="${h.number||raceBody.children.length+1}"></td>
  <td class="horse-name"><input class="race-input h-name" placeholder="Nom du cheval" value="${escapeHtml(h.name||'')}"><span class="horse-sub h-meta">${escapeHtml(h.age||'')} ${escapeHtml(h.sex||'')}</span></td>
  <td><select class="base-select">${profileOptions(h.profileId)}</select></td>
  <td><input class="race-input h-jockey" placeholder="Jockey" value="${escapeHtml(h.jockey||'')}"></td>
  <td><input class="race-input h-weight" type="number" step="0.5" value="${h.weight||''}"></td>
  <td><input class="race-input h-value" type="number" step="0.5" value="${h.value||''}"></td>
  <td><input class="race-input h-draw" type="number" min="1" value="${h.draw||''}"></td>
  <td><span class="form-dots">${escapeHtml(h.form||'—')}</span></td>
  <td><input class="race-input h-speed" type="number" step="0.1" value="${h.speed||''}"></td>
  <td><select class="race-input h-tactic"><option ${h.tactic==='Attentiste'?'selected':''}>Attentiste</option><option ${h.tactic==='Régulier'?'selected':''}>Régulier</option><option ${h.tactic==='Lièvre'?'selected':''}>Lièvre</option><option ${h.tactic==='Finisseur'?'selected':''}>Finisseur</option></select></td>
  <td><b class="score">—</b><details><summary>critères</summary><div class="score-grid">${scoreInputs(h.scores||{})}</div></details></td><td><button class="delete" type="button" title="Retirer">×</button></td>`;
  tr.querySelector('.delete').onclick=()=>tr.remove();
  tr.querySelector('.base-select').onchange=e=>applyProfileToRace(tr, profiles.find(p=>String(p.id)===e.target.value));
  raceBody.append(tr); return tr;
}
function applyProfileToRace(tr,p){if(!p)return; tr.dataset.profileId=p.id; tr.querySelector('.h-name').value=p.name||''; tr.querySelector('.h-jockey').value=p.jockey||''; tr.querySelector('.h-value').value=p.value||''; tr.querySelector('.h-speed').value=p.speed||''; tr.querySelector('.h-tactic').value=p.tactic||'Attentiste'; tr.querySelector('.h-meta').textContent=`${ageOf(p.birthdate)||''} ${p.sex||''}`.trim(); tr.querySelectorAll('.race-score').forEach(input=>input.value=p.scores?.[input.dataset.key]??'');}
function collectRace(){return {id:currentRaceId,name:value('race-name'),track:value('track'),distance:num(value('distance')),ground:value('ground'),weights:Object.fromEntries(criteria.map(([k])=>[k,num(document.querySelector(`[data-weight="${k}"]`)?.value)||0])),horses:[...raceBody.children].map(tr=>({profileId:tr.dataset.profileId||null,number:num(tr.querySelector('.horse-num').value),name:tr.querySelector('.h-name').value.trim(),jockey:tr.querySelector('.h-jockey').value.trim(),weight:num(tr.querySelector('.h-weight').value),value:num(tr.querySelector('.h-value').value),draw:num(tr.querySelector('.h-draw').value),speed:num(tr.querySelector('.h-speed').value),tactic:tr.querySelector('.h-tactic').value,scores:Object.fromEntries([...tr.querySelectorAll('.race-score')].map(i=>[i.dataset.key,num(i.value)]))}))}}
function renderRanking(list){[...raceBody.children].forEach(tr=>{const number=num(tr.querySelector('.horse-num').value);const item=list.find(x=>x.number===number);tr.querySelector('.score').textContent=item?item.note.toFixed(1):'—'});const best=list.slice(0,5);$('#selection').innerHTML=best.length?best.map((h,i)=>`<div class="pick"><strong>${i+1}</strong><span>${escapeHtml(h.name)}</span><small>${h.note.toFixed(1)}/100</small></div>`).join(''):'<span>Ajoutez des chevaux pour obtenir une sélection.</span>';$('#analysis').innerHTML=best.length?[`<li>${escapeHtml(best[0].name)} prend la tête avec une note de ${best[0].note.toFixed(1)}.</li>`,`<li>${best.length} chevaux sont comparés avec les critères Gérard.</li>`,`<li>Les fiches sélectionnées sont chargées depuis votre base locale.</li>`].join(''):'<li>Ajoutez les chevaux de la course pour lancer l’analyse.</li>'}
async function rank(){try{const r=collectRace();const list=await api('/api/rank','POST',r);renderRanking(list);$('#status').textContent='Classement recalculé.'}catch(e){$('#status').textContent=e.message;$('#status').style.color='#c0263c'}}
function buildProfileScores(scores={}){$('#profile-score-fields').innerHTML=scoreInputs(scores,'profile')}
function readProfile(){const p={id:value('profile-id')||null,name:value('profile-name'),scores:{}};fields.forEach(f=>{p[f]=value(profileFieldId(f))});p.equipment=[...document.querySelectorAll('input[name="equipment"]:checked')].map(i=>i.value);['value','lastValue','speed'].forEach(f=>p[f]=num(p[f]));document.querySelectorAll('.profile-score').forEach(i=>{const n=num(i.value);if(n!==null)p.scores[i.dataset.key]=n});return p}
function fillProfile(p={}){$('#horse-form').reset();$('#profile-id').value=p.id||'';$('#profile-name').value=p.name||'';fields.forEach(f=>{const el=$(profileFieldId(f));if(el)el.value=p[f]??''});document.querySelectorAll('input[name="equipment"]').forEach(i=>i.checked=(Array.isArray(p.equipment)?p.equipment:String(p.equipment||'').split(',')).includes(i.value));buildProfileScores(p.scores||{});$('#delete-horse').classList.toggle('hidden',!p.id);$('#horse-form').classList.remove('hidden');$('#horse-status').textContent=p.id?`Fiche de ${p.name} ouverte.`:''}
function renderProfiles(){const list=$('#profile-list'), query=value('horse-search').toLowerCase();const shown=profiles.filter(p=>[p.name,p.sex,p.robe,p.trainer].some(v=>String(v||'').toLowerCase().includes(query)));if(!shown.length){list.innerHTML=`<tr><td colspan="7">${profiles.length?'Aucun cheval ne correspond à la recherche.':'Aucun cheval enregistré pour le moment.'}</td></tr>`;return}list.innerHTML=shown.map(p=>`<tr data-id="${p.id}"><td><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.robe||'Non renseignée')}</small></td><td>${ageOf(p.birthdate)||'—'}</td><td>${escapeHtml(p.sex||'—')}</td><td>${escapeHtml(p.trainer||'—')}</td><td>${p.value??'—'}</td><td>${escapeHtml(p.discipline||'—')}</td><td><button class="outline open-profile" type="button">Ouvrir</button></td></tr>`).join('');list.querySelectorAll('tr[data-id]').forEach(row=>row.onclick=e=>{if(e.target.closest('button')||e.target.tagName!=='BUTTON')fillProfile(profiles.find(p=>String(p.id)===row.dataset.id))});list.querySelectorAll('.open-profile').forEach(b=>b.onclick=()=>fillProfile(profiles.find(p=>String(p.id)===b.closest('tr').dataset.id)));}
async function loadProfiles(){profiles=await api('/api/horses');renderProfiles();$('#horse-names').innerHTML=profiles.map(p=>`<option value="${escapeHtml(p.name)}">`).join('');const people=[...new Set([...profiles.flatMap(p=>[p.trainer,p.owner,p.jockey,p.jockeyAlt]),...jockeys.map(j=>j.name)].filter(Boolean))];$('#people-names').innerHTML=people.map(name=>`<option value="${escapeHtml(name)}">`).join('');raceBody.querySelectorAll('.base-select').forEach(select=>{const selected=select.value;select.innerHTML=profileOptions(selected)})}
async function seedProfiles(){if(profiles.length)return;const common={birthdate:'2021-04-15',sex:'Hongre',groundPref:'Souple',endurance:'Bonne',constance:'Bonne',equipment:'Œillères',scores:{classe:8,forme:8,vitesse:8,confrontations:7,valeur:7,poids:7,corde:7,terrain:8,distance:8,parcours:7,tactique:7,age_sexe:7,entourage:8}};const examples=[{name:'Sultan du Nord',robe:'Bai',trainer:'J.-M. Bazire',jockey:'M. Abrivard',value:38.5,lastValue:39,speed:57.8,tactic:'Régulier',distancePref:'1 600 à 2 000 m',notes:'Très bon finish, apprécie les terrains souples.'},{name:'Golden River',robe:'Alezan',trainer:'F. Rohaut',jockey:'C. Soumillon',value:39,lastValue:39.5,speed:58.4,tactic:'Attentiste',distancePref:'1 600 à 2 400 m',notes:'Régulier et bien placé au poids.'},{name:'Belle Étoile',sex:'Femelle',robe:'Bai brun',trainer:'A. Fabre',jockey:'A. Lemaitre',value:37,lastValue:37.5,speed:55.9,tactic:'Finisseur',distancePref:'1 800 à 2 400 m',notes:'Toujours dans le coup, belle tenue.'}];await Promise.all(examples.map(example=>api('/api/horses','POST',{...common,...example,scores:{...common.scores,...(example.scores||{})}})));await loadProfiles()}
function readJockey(){return {id:value('jockey-id')||null,name:value('jockey-name'),age:num(value('jockey-age')),weight:num(value('jockey-weight')),stable:value('jockey-stable'),roles:[...document.querySelectorAll('input[name="role"]:checked')].map(i=>i.value),successRate:num(value('jockey-successRate')),rides:num(value('jockey-rides')),softRate:num(value('jockey-softRate')),heavyRate:num(value('jockey-heavyRate')),shortRate:num(value('jockey-shortRate')),middleRate:num(value('jockey-middleRate')),longRate:num(value('jockey-longRate')),tracks:value('jockey-tracks'),notes:value('jockey-notes')}}
function fillJockey(j={}){$('#jockey-form').reset();$('#jockey-id').value=j.id||'';['name','age','weight','stable','successRate','rides','softRate','heavyRate','shortRate','middleRate','longRate','tracks','notes'].forEach(k=>$('#jockey-'+k).value=j[k]??'');document.querySelectorAll('input[name="role"]').forEach(i=>i.checked=(j.roles||['jockey']).includes(i.value));$('#delete-jockey').classList.toggle('hidden',!j.id);$('#jockey-status').textContent=j.id?`Fiche de ${j.name} ouverte.`:''}
function renderJockeys(){const list=$('#jockey-list');if(!jockeys.length){list.innerHTML='<p>Aucun profil enregistré pour le moment.</p>';return}list.innerHTML=jockeys.map(j=>`<button type="button" class="profile-item" data-id="${j.id}"><strong>${escapeHtml(j.name)}</strong><small>${escapeHtml((j.roles||[]).join(' · ')||'Jockey')} · réussite ${j.successRate??'—'} %</small></button>`).join('');list.querySelectorAll('.profile-item').forEach(b=>b.onclick=()=>fillJockey(jockeys.find(j=>String(j.id)===b.dataset.id)))}
async function loadJockeys(){jockeys=await api('/api/jockeys');renderJockeys()}
async function saveJockey(e){e.preventDefault();try{const saved=await api('/api/jockeys','POST',readJockey());await loadJockeys();fillJockey(saved);$('#jockey-status').textContent=`${saved.name} est enregistré.`;$('#jockey-status').style.color='#087a41'}catch(err){$('#jockey-status').textContent=err.message;$('#jockey-status').style.color='#c0263c'}}
async function deleteJockey(){const id=value('jockey-id');if(!id)return;try{await api('/api/jockeys/'+id,'DELETE');await loadJockeys();fillJockey();$('#jockey-status').textContent='Profil supprimé.'}catch(err){$('#jockey-status').textContent=err.message;$('#jockey-status').style.color='#c0263c'}}
function showView(name){$('#pronostics-view').classList.toggle('hidden',name!=='pronostics');$('#horse-view').classList.toggle('hidden',name!=='horse');$('#jockey-view').classList.toggle('hidden',name!=='jockey');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===name&&(name==='horse'?b.id==='add-side':name==='jockey'?b.id==='jockeys-nav':b.id==='pronostics-nav')));window.scrollTo({top:0,behavior:'smooth'})}
async function saveHorse(e){e.preventDefault();try{const saved=await api('/api/horses','POST',readProfile());await loadProfiles();fillProfile(saved);$('#horse-status').textContent=`${saved.name} est enregistré dans votre base locale.`;$('#horse-status').style.color='#087a41'}catch(err){$('#horse-status').textContent=err.message;$('#horse-status').style.color='#c0263c'}}
async function deleteHorse(){const id=value('profile-id');if(!id)return;try{await api('/api/horses/'+id,'DELETE');await loadProfiles();$('#horse-form').classList.add('hidden');fillProfile({});$('#horse-form').classList.add('hidden');$('#horse-status').textContent='Cheval supprimé.'}catch(err){$('#horse-status').textContent=err.message;$('#horse-status').style.color='#c0263c'}}
async function init(){criteria=await api('/api/config');$('#today').textContent=new Intl.DateTimeFormat('fr-FR',{dateStyle:'full'}).format(new Date());$('#weight-fields').innerHTML=criteria.map(([k,l,d])=>`<label>${l}<input data-weight="${k}" type="number" min="0" max="100" value="${d}"></label>`).join('');buildProfileScores();await Promise.all([loadProfiles(),loadJockeys()]);await seedProfiles();demo();}
function demo(){const demo=[['Sultan du Nord',58,38.5,57.8,'Régulier',[8,9,9]],['Golden River',57,39,58.4,'Attentiste',[8,8,10]],['Lady Charm',56,40,56.1,'Attentiste',[7,7,8]],['Thunder Wind',57,40.5,55.2,'Lièvre',[7,6,6]],['Belle Étoile',55,37,55.9,'Régulier',[8,8,7]],['Roi du Ciel',56,36.5,57.1,'Attentiste',[7,8,8]]];demo.forEach((x,i)=>{const scores=Object.fromEntries(criteria.map(([k],n)=>[k,n<3?x[5][n]:7]));addHorse({number:i+1,name:x[0],jockey:['M. Abrivard','C. Soumillon','M. Barzalona','R. Thomas','A. Lemaitre','T. Bachelot'][i],weight:x[1],value:x[2],draw:(i%7)+1,speed:x[3],tactic:x[4],form:'● ● ● ●',scores})});rank()}
$('#race-form').onsubmit=async e=>{e.preventDefault();try{const r=collectRace();const saved=await api('/api/races','POST',r);currentRaceId=saved.id;await rank();$('#status').textContent='Course et classement enregistrés.'}catch(err){$('#status').textContent=err.message;$('#status').style.color='#c0263c'}};
$('#add').onclick=()=>addHorse();$('#weights').onclick=()=>$('#weight-panel').classList.remove('hidden');$('#close-weights').onclick=()=>$('#weight-panel').classList.add('hidden');$('#horse-form').onsubmit=saveHorse;$('#new-horse').onclick=()=>{const form=$('#horse-form');if(form.classList.contains('hidden'))fillProfile();else form.classList.add('hidden')};$('#delete-horse').onclick=deleteHorse;$('#horse-search').oninput=renderProfiles;document.querySelectorAll('.accordion-title').forEach(b=>b.onclick=()=>b.closest('.accordion').classList.toggle('closed'));$('#jockey-form').onsubmit=saveJockey;$('#new-jockey').onclick=()=>fillJockey();$('#delete-jockey').onclick=deleteJockey;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));init().catch(e=>$('#status').textContent=e.message);
