const $=s=>document.querySelector(s);
let criteria=[],currentId=null,history=[],dirty=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(text,error=false){$('#status').textContent=text;$('#status').className=error?'error':'';}
async function api(path,data){const r=await fetch('/api/'+path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const result=await r.json();if(!r.ok)throw Error(result.error||'Erreur du serveur');return result;}
function guarded(fn){return async(...args)=>{try{await fn(...args);}catch(e){status(e.message,true);}};}
function mark(){dirty=true;$('#saved-state').textContent='Modifications non enregistrées';$('#results').innerHTML='<p class="empty">Recalculez pour actualiser le classement.</p>';}
const rawFields=[['number','N°','number'],['name','Nom du cheval','text'],['draw','Corde','number'],['value','Valeur handicap','number'],['weight','Poids porté (kg)','number'],['allowance','Décharge constatée (kg)','number'],['class','Classe affrontée','text'],['speed','Vitesse comparable (km/h)','number'],['age','Âge','number'],['sex','Sexe','text'],['tactic','Profil tactique','text'],['jockey','Jockey / driver','text'],['trainer','Entraîneur','text'],['form','Cinq dernières courses','text'],['finish','Place à l’arrivée','number']];
function addHorse(h={}){const el=document.createElement('details');el.className='horse';el.open=true;el.innerHTML=`<summary>${esc(h.number||'Nouveau')} · ${esc(h.name||'Cheval à renseigner')}</summary><div class="fields">${rawFields.map(([k,l,t])=>`<label>${l}<input data-field="${k}" type="${t}" ${t==='number'?'min="0" step="any"':''} ${k==='name'||k==='number'?'required':''} value="${esc(h[k])}"></label>`).join('')}</div><label>Observations et confrontations<textarea data-field="notes" rows="2">${esc(h.notes)}</textarea></label><h3>Évaluations des aptitudes · / 10</h3><div class="fields scores">${criteria.map(([k,l])=>`<label>${l}<input data-score="${k}" type="number" min="0" max="10" step="0.1" placeholder="Inconnu" value="${esc(h.scores?.[k])}"></label>`).join('')}</div><button type="button" class="remove">Retirer ce cheval</button>`;
el.querySelector('.remove').onclick=()=>{if(confirm('Retirer ce cheval de l’analyse ?')){el.remove();mark();}};el.addEventListener('input',()=>{el.querySelector('summary').textContent=`${el.querySelector('[data-field="number"]').value||'Nouveau'} · ${el.querySelector('[data-field="name"]').value||'Cheval à renseigner'}`;});$('#horses').append(el);}
function collect(){if(!$('#race-form').reportValidity())throw Error('Complétez les champs obligatoires et vérifiez les nombres.');const race={id:currentId,weights:{},horses:[]};for(const key of ['name','date','track','distance','ground','discipline'])race[key]=$('#race-'+key).value;document.querySelectorAll('[data-weight]').forEach(e=>race.weights[e.dataset.weight]=Number(e.value));document.querySelectorAll('.horse').forEach(el=>{const h={scores:{}};el.querySelectorAll('[data-field]').forEach(e=>h[e.dataset.field]=e.value);el.querySelectorAll('[data-score]').forEach(e=>h.scores[e.dataset.score]=e.value===''?null:Number(e.value));race.horses.push(h);});return race;}
function load(r={}){currentId=r.id??null;for(const k of ['name','date','track','distance','ground','discipline'])$('#race-'+k).value=r[k]??(k==='discipline'?'Plat':k==='date'?new Date().toLocaleDateString('en-CA'):'');$('#weights').innerHTML=criteria.map(([k,l,w])=>`<label>${l}<input data-weight="${k}" type="number" min="0" max="100" step="0.1" required value="${r.weights?.[k]??w}"></label>`).join('');$('#horses').innerHTML='';(r.horses||[]).forEach(addHorse);$('#results').innerHTML='<p class="empty">Calculez pour afficher le classement.</p>';dirty=false;$('#saved-state').textContent=currentId?'Course enregistrée':'Nouvelle analyse';}
async function refresh(){history=await api('races');$('#history').innerHTML='';for(const r of history){const b=document.createElement('button');b.textContent=`${r.name} · ${r.date||'Sans date'}`;b.onclick=guarded(async()=>{if(dirty&&!confirm('Quitter cette analyse sans enregistrer les modifications ?'))return;load(r);await rank();status('Course chargée depuis l’historique.');});$('#history').append(b);}}
async function rank(){const rows=await api('rank',collect());$('#results').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Rang</th><th>Cheval</th><th>Note</th><th>Couverture</th><th>Arrivée</th></tr></thead><tbody>${rows.map((h,i)=>`<tr><td>${i+1}</td><td><b>${esc(h.number)} · ${esc(h.name)}</b><details><summary>Détail des points</summary>${criteria.map(([k,l])=>`<p>${l} : ${h.scores[k]??'inconnu'}/10 → ${h.details[k]} pts</p>`).join('')}</details></td><td><strong>${h.note.toFixed(1)}</strong></td><td>${h.coverage} %</td><td>${esc(h.finish)||'—'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty">Ajoutez au moins un cheval.</p>';}
$('#race-form').addEventListener('input',mark);
$('#race-form').onsubmit=guarded(async e=>{e.preventDefault();await rank();status('Classement calculé. Enregistrez pour conserver cette analyse.');});
$('#add').onclick=()=>{addHorse();mark();};
$('#new').onclick=()=>{if(dirty&&!confirm('Quitter sans enregistrer ?'))return;load();status('Nouvelle course prête à renseigner.');};
$('#save').onclick=guarded(async()=>{const result=await api('races',collect());currentId=result.id;dirty=false;$('#saved-state').textContent='Course enregistrée';await refresh();status('Course et évaluations enregistrées dans SQLite.');});
$('#export').onclick=guarded(async()=>{const race=collect();await api('rank',race);const blob=new Blob([JSON.stringify(race,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='course-gerard.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Export JSON téléchargé.');});
$('#demo').onclick=guarded(async()=>{if(dirty&&!confirm('Remplacer la saisie par l’exemple ?'))return;load({name:'Prix des Amandiers · Démonstration',date:'2026-09-27',track:'Hippodrome fictif',distance:2000,ground:'Souple',discipline:'Plat',horses:['Étoile du Matin','Grand Horizon','Belle Allure'].map((name,i)=>({number:i+1,name,draw:i+2,age:4+i,sex:i===2?'F':'H',weight:58-i,value:40-i,class:'Classe 2',tactic:['Finisseur','Animateur','Attentiste'][i],notes:'Données fictives pour découvrir le prototype.',scores:Object.fromEntries(criteria.map(([k],j)=>[k,i===2&&j>8?null:Math.max(0,9-i-(j%3))]))}))});mark();await rank();status('Exemple fictif chargé. Enregistrez-le pour le conserver.');});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
guarded(async()=>{criteria=await api('config');load();await refresh();})();
